### ISSUE TITLE
参考文献字号不对，应该是小四

### ISSUE THREAD

**Issue by fanminhao** [NWPUMetaphysicsOffice/LaTeX-Template-For-NPU-PhD-Master-Thesis#13]

**Comment by fanminhao** [comment]
有人嘛！！

**Comment by polossk** [comment]
我们正在更正，如果您着急，可以自己写一份

**Comment by polossk** [comment]
@fanminhao 您好，这边但凡收到了issue都会第一时间在修正并回复，您自己也能看到发的pr和commit。
但是您也是硕博研究生，应该知道我们的科研时间都很宝贵，我们组内的人不可能一直在线等着issue出现。
下次再催更直接永久block，爱用不用。

**Comment by fanminhao** [comment]
只是开玩笑，辛苦啦，下次注意⚠️



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Shangkun Shen <notifications@github.com&gt;
发送时间: 2020年10月15日 22:01
收件人: NWPUMetaphysicsOffice/LaTeX-Template-For-NPU-PhD-Master-Thesis <LaTeX-Template-For-NPU-PhD-Master-Thesis@noreply.github.com&gt;
抄送: fmhhhhhh <439038381@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[NWPUMetaphysicsOffice/LaTeX-Template-For-NPU-PhD-Master-Thesis] 参考文献字号不对，应该是小四 (#13)





 
@fanminhao 您好，这边但凡收到了issue都会第一时间在修正并回复，您自己也能看到发的pr和commit。
 但是您也是硕博研究生，应该知道我们的科研时间都很宝贵，我们组内的人不可能一直在线等着issue出现。
 下次再催更直接永久block，爱用不用。
