### ISSUE TITLE
sublime 上运行不了

### ISSUE THREAD

**Issue by HandsomeWeiC** [NWPUMetaphysicsOffice/LaTeX-Template-For-NPU-PhD-Master-Thesis#3]
运行document.tex 文件会出现 CJKnumb.sty:67: Undefined control sequence. [\CJKaddEncHook] 这个错误，请问怎么解决？
![image](https://user-images.githubusercontent.com/27289446/69156989-3fc52d80-0b1f-11ea-8c93-e3ee6e830603.png)

**Comment by kidozh** [comment]
我使用的是Tex Live 2019+sublime Text 3 目前build with xlatexmk是通过的。

从你的这个配置来看，看起来像是没有相应的库，是不是latex来源对应不上？你可以使用Tex Live 2019重试一下。

**Comment by HandsomeWeiC** [comment]
我之前安装的是CTEX，那就是用不了了吗？感觉是不是MIKTEX没有CJK这个库啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kido Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午3:12
收件人:&nbsp;"NWPUMetaphysicsOffice/LaTeX-Template-For-NPU-PhD-Master-Thesis"<LaTeX-Template-For-NPU-PhD-Master-Thesis@noreply.github.com&gt;;
抄送:&nbsp;"2935724518"<2935724518@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NWPUMetaphysicsOffice/LaTeX-Template-For-NPU-PhD-Master-Thesis] sublime 上运行不了 (#3)




我使用的是Tex Live 2019+sublime Text 3 目前build with xlatexmk是通过的。
 
从你的这个配置来看，看起来像是没有相应的库，是不是latex来源对应不上？你可以使用Tex Live 2019重试一下。

**Comment by kidozh** [comment]
看起来是这样的，你也可以使用xecjk和xetex试一试，但是可能需要对代码设置这一块调整很多。

还是建议使用项目readme里面写的tex live 2017以及以上版本编译，miktex感觉有点老了。

学校下texlive的ISO还是很快的

**Comment by HandsomeWeiC** [comment]
恩恩，好的，谢谢啦！！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kido Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午3:25
收件人:&nbsp;"NWPUMetaphysicsOffice/LaTeX-Template-For-NPU-PhD-Master-Thesis"<LaTeX-Template-For-NPU-PhD-Master-Thesis@noreply.github.com&gt;;
抄送:&nbsp;"2935724518"<2935724518@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NWPUMetaphysicsOffice/LaTeX-Template-For-NPU-PhD-Master-Thesis] sublime 上运行不了 (#3)




看起来是这样的，你也可以使用xecjk和xetex试一试，但是可能需要对代码设置这一块调整很多。
 
还是建议使用项目readme里面写的tex live 2017以及以上版本编译，miktex感觉有点老了。
 
学校下texlive的ISO还是很快的

**Comment by kidozh** [comment]
有什么问题可以发issue过来，那我先关这个issue了，有新的问题你也可以重新打开这个issue或者新开一个issue。那就这样了。

**Comment by HandsomeWeiC** [comment]
感谢大佬，还真是MIKTEX的原因，安装了TexLive就可以运行了，感谢感谢！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kido Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午3:40
收件人:&nbsp;"NWPUMetaphysicsOffice/LaTeX-Template-For-NPU-PhD-Master-Thesis"<LaTeX-Template-For-NPU-PhD-Master-Thesis@noreply.github.com&gt;;
抄送:&nbsp;"2935724518"<2935724518@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NWPUMetaphysicsOffice/LaTeX-Template-For-NPU-PhD-Master-Thesis] sublime 上运行不了 (#3)




Closed #3.
