### ISSUE TITLE
摘要和目录的页码

### ISSUE THREAD

**Issue by likunyao** [NWPUMetaphysicsOffice/LaTeX-Template-For-NPU-PhD-Master-Thesis#5]
你好，摘要和目录的页码应该是罗马数字大写，tex文件中是大写Roman，但是生成的pdf文件是小写

**Comment by cfrpg** [comment]
您好，感谢反馈。
问题已经定位，目前暂时的解决方案是将`\pagenumbering{Roman}`放置到摘要前的`\clearpage`前（约41行）。

**Comment by polossk** [comment]
@cfrpg 请及时PR

**Comment by polossk** [comment]
@likunyao 模板已更新，请下载最新版本

对应 commit ` 9b44867cd4fd55cedc14e073da965f42d4b30536`
